/**
 * questions.ts — 真心话大冒险题库
 *
 * 三档主题：
 *   icebreaker — 破冰版，群里不太熟也能玩
 *   advanced   — 进阶版，涉及感情、社交、小秘密
 *   spicy      — 激情版，暧昧/性暗示/醉酒强度，18+ 但不露骨
 *
 * 目标用户：18-26 岁，俄罗斯/印尼/印度/美国年轻人
 * 印尼和印度用户用英文版（Telegram 上这两个市场年轻人普遍用英语）
 */

import { randomInt } from 'node:crypto';

export type TodTier = 'icebreaker' | 'advanced' | 'spicy';

export interface QuestionBank {
  truth: string[];
  dare: string[];
}

export type TieredQuestionBank = Record<TodTier, QuestionBank>;

// ─── English ─────────────────────────────────────────────────────────────────

const EN: TieredQuestionBank = {
  icebreaker: {
    truth: [
      "What's the last thing you googled? Be honest",
      "What's a skill you've been pretending to have?",
      "What's the most embarrassing song on your playlist?",
      "Who in this group would you swap lives with for a day?",
      "What's the weirdest rabbit hole you've gone down on YouTube?",
      "What's your most controversial food opinion?",
      "What app do you waste the most time on?",
      "What's a trend you secretly think is stupid?",
      "If your search history was leaked, what would ruin you?",
      "What's something you're weirdly competitive about?",
      "What's the pettiest reason you've unfollowed someone?",
      "What's the longest you've stalked someone's profile?",
      "What's a lie you've told on your bio or dating profile?",
      "What's the most unhinged thing on your saved reels?",
      "If everyone in this group could see your screen time, what would shock them?",
      "What's a hill you will absolutely die on?",
      "What's your most used emoji and what does that say about you?",
      "What's the worst impulse purchase you've made?",
      "What's a compliment you got that you still think about?",
      "What's the last white lie you told today?",
      "What's something you judge people for but do yourself?",
      "Who was your most embarrassing celebrity crush?",
      "What's the most chaotic thing in your camera roll right now?",
      "What's one thing you'd change about your morning routine?",
      "What movie do you pretend to have seen but never actually watched?",
      "What's the worst DM you've ever sent?",
      "What's the most random thing you've cried over?",
      "What did you want to be when you were 10?",
      "What's a conspiracy theory you low-key believe?",
      "Who in this group gives the best memes?",
    ],
    dare: [
      'Show the last photo in your camera roll — no deleting first',
      'Send a voice message doing your best movie villain impression',
      'Type your next 3 messages with your eyes closed, send as-is',
      'Let the group pick your profile pic for the next hour',
      'Send the 7th photo in your gallery with zero context',
      'Voice message: do your best impression of someone in this group',
      'Screenshot your screen time and post it',
      'Post a selfie right now, no filter, no retake',
      'Text "I need to tell you something important" to the 3rd person in your recent chats',
      'Let someone in the group post a story/status from your account',
      'Send a voice note singing whatever song is stuck in your head',
      'Reply to the next 3 messages using only GIFs',
      'Share the last meme you sent to someone',
      'Change your bio to whatever the group decides for 30 minutes',
      'Send a compliment to every person in this group right now',
      'Do a dramatic reading of your last sent text via voice message',
      "Send a screenshot of your most recent chat (blur names if you're scared)",
      'Use only caps lock for the next 5 messages',
      'Record yourself saying a tongue twister in another language',
      'Send the oldest selfie you can find on your phone',
      'Let the group write a message and you send it to your best friend',
      'Share your top 3 most played songs this week',
      'Post a screenshot of your notes app — unedited',
      'Describe everyone in this group with one emoji each',
      'Send a voice message whispering a fun fact about yourself',
      'Text your most recent contact "hey, thinking about you"',
      'Put your music on shuffle and share whatever plays first',
      "Share a screenshot of your most embarrassing notification that's still on your phone",
      'Reply only in questions for the next 5 messages',
      'Send a sticker that best represents your current mood',
    ],
  },

  advanced: {
    truth: [
      "What's the biggest lie you've told someone you care about?",
      "Who was your last crush and does anyone here know them?",
      "What's the most toxic trait you know you have?",
      "Have you ever stayed in a relationship longer than you should have? Why?",
      "What's something you've done drunk that you've never told anyone?",
      "Who in this group do you think has the best love life?",
      "Have you ever screenshot a conversation to send to someone else?",
      "What's the worst thing you've said about someone behind their back?",
      "Who's the one that got away?",
      "Have you ever caught feelings for someone in this group?",
      "What's a red flag you've ignored because someone was attractive?",
      "What's the most desperate thing you've done for attention?",
      "Have you ever dated someone your friends hated?",
      "What's the biggest secret you're keeping from your family?",
      "Who do you text the most and what would people think if they read those chats?",
      "Have you ever lied to get out of plans and then posted on social media?",
      "What's the shadiest thing you've done on a dating app?",
      "Who was the last person you creeped on Instagram/Telegram?",
      "Have you ever pretended to be offline to avoid someone?",
      "What relationship advice do you give others but never follow yourself?",
      "Have you ever been jealous of someone in this group? About what?",
      "What's a secret you'd only tell in this chat?",
      "What's the worst excuse you've used to cancel on someone?",
      "Have you ever had a friend you secretly couldn't stand?",
      "What's the most embarrassing thing someone has caught you doing?",
      "Who would you call if you had to bail someone out at 3 AM?",
      "Have you ever read someone's messages without them knowing?",
      "What's a boundary you've crossed that you regret?",
      "If we could all see your Spotify/YouTube history from last night, what would we find?",
      "What's the most emotionally unavailable thing you've ever done?",
    ],
    dare: [
      "DM someone you haven't talked to in months and say 'I had a dream about you'",
      "Post your lock screen — no changing it first",
      "Let the group go through your following list and ask about any 3 people",
      "Send a voice message confessing something small you've never admitted",
      "Text your ex or old crush 'hey' and screenshot the result",
      "Share the last person you searched on Instagram/Telegram",
      "Let someone in the group send one message from your account to anyone",
      "Post a screenshot of your 'saved' or 'bookmarked' posts",
      "Record a voice note telling someone in this group what you really think of them",
      "Share the most flirty DM you've ever received",
      "Send the last voice message you received — no context",
      "Let the group choose who you have to compliment in a voice note",
      "Post a photo from a night out that you'd never put on your main",
      "Share your phone's battery percentage and your last searched emoji",
      "Text someone 'we need to talk' and wait 5 minutes before explaining",
      "Share a screenshot of how many unread messages you have",
      "Let the group pick a song and you have to sing it in a voice message",
      "Share a photo of yourself from exactly one year ago",
      "Write a fake thirst trap caption and post it here",
      "Call someone on your contact list on speaker and let the group listen for 10 seconds",
      "Text the last person you matched with on a dating app something bold",
      "Post the most chaotic photo in your recently deleted",
      "Share a hot take that might make someone here mad",
      "Switch your pfp to whatever the group votes on for 2 hours",
      "Let someone ghost-write your next Instagram/Telegram story",
      "Voice message: say three nice things about the person above you",
      "Share a guilty pleasure playlist or song you hide from everyone",
      "Reply to an old story/status of someone in this group with a fire emoji",
      "Describe your type without naming anyone — group guesses who you're thinking of",
      "Post a screenshot of the last thing you added to cart online",
    ],
  },

  spicy: {
    truth: [
      "What's the most flirty message sitting in your DMs right now?",
      "Who in this group would you most likely have tension with at a party?",
      "What's your body count — or at least what do you tell people it is?",
      "Have you ever sent a risky photo you regret?",
      "What's the wildest thing on your private story that you'd never post publicly?",
      "Who was the last person you had a dream about that you shouldn't have?",
      "What's the most scandalous thing you've done that nobody here knows about?",
      "Have you ever been the 'other' person? What happened?",
      "What's your biggest turn-on that you've never told anyone?",
      "Who in this group has flirty energy and doesn't even know it?",
      "What's something you've done at a party that you'll never admit sober?",
      "Who do you think about when you hear 'what if'?",
      "Have you ever caught feelings for someone you were only supposed to hook up with?",
      "What's the most forward thing you've ever said to someone you were into?",
      "What's a fantasy scenario you think about but would never act on?",
      "Have you ever faked interest in someone just to get something?",
      "What's the riskiest place you've ever been intimate?",
      "What do people assume about your love life that's completely wrong?",
      "Who was the worst kisser you've ever experienced?",
      "Have you ever had feelings for two people at the same time? Who won?",
      "What's the most embarrassing thing that's happened to you on a date?",
      "If you could have a no-consequences night with anyone, who would it be?",
      "What's the boldest move you've ever made on someone?",
      "Have you ever used someone's Netflix/Spotify after things ended?",
      "What's a message in your DMs that would shock this group?",
      "What physical feature do you notice first on someone you're attracted to?",
      "Have you ever lied about where you slept last night?",
      "What's the most unhinged thing you've done when jealous?",
      "If your situationship had a status update, what would it say?",
      "Who in this group do you think has the most interesting private life?",
    ],
    dare: [
      "Send your most attractive selfie to this chat — own it",
      "DM someone in this group something you'd only say at 2 AM",
      "Let the group read your last 3 DMs (you pick which chat, but no editing)",
      "Voice message: describe your ideal type in detail — the group guesses who fits",
      "Post the thirstiest photo on your phone — or the group picks your pfp for 3 hours",
      "Text your crush or situationship 'come over' and screenshot the reply",
      "Share the last emoji you used in a flirty conversation",
      "Let the group write a pickup line and you have to DM it to someone",
      "Send a voice message with your best 'flirty voice' saying anything",
      "Share a song that reminds you of someone you've been with — no context",
      "Rate everyone in this group 1-10 on 'mysterious energy' — voice message only",
      "Post a thirst trap selfie in this chat right now — no deleting for 10 min",
      "Let someone pick a contact and you have to send them a fire emoji with no explanation",
      "Describe your last situationship in exactly 5 words",
      "Voice message: give your hottest take on what makes someone attractive",
      "Share the boldest text you've ever sent to someone you were into",
      "Let the group write your dating app bio for the next 24 hours",
      "Record a voice message reading the last flirty text you sent — no editing",
      "Pick someone in this group and give them your most genuine compliment via voice note",
      "Post a screenshot of your 'type' — could be a celeb, character, or aesthetic",
      "Text someone 'I can't stop thinking about you' and show the response",
      "Whisper something in a voice note that you'd only say in person",
      "Share the most chaotic screenshot in your phone — the group picks if it stays up",
      "Send a 🔥 emoji to 3 people in your DMs with no explanation",
      "Let the group dare you to text anything to anyone — you have one veto",
      "Post a photo of your fit check right now — the group rates it",
      "Send a voice note saying 'I like you' in three different languages",
      "Share your most played late-night song — no lying",
      "Describe your last dream about someone without saying who — group guesses",
      "Post 'drop a 🔥 if you think I'm attractive' on your story/status and screenshot the results",
    ],
  },
};

// ─── Russian ─────────────────────────────────────────────────────────────────

const RU: TieredQuestionBank = {
  icebreaker: {
    truth: [
      'Что последнее ты гуглил(а)? Честно',
      'Какой навык ты притворяешься, что имеешь?',
      'Какая самая стыдная песня в твоём плейлисте?',
      'С кем из группы ты бы поменялся жизнью на день?',
      'Самая странная кроличья нора, в которую ты залезал(а) на YouTube?',
      'Твоё самое спорное мнение о еде?',
      'В каком приложении ты тратишь больше всего времени?',
      'Какой тренд ты втайне считаешь тупым?',
      'Если бы твою историю поиска слили — что бы тебя погубило?',
      'В чём ты странно конкурентен(а)?',
      'Самая мелочная причина, по которой ты отписался от кого-то?',
      'Сколько максимум ты листал(а) чей-то профиль вглубь?',
      'Что ты приврал(а) в своём био или на сайте знакомств?',
      'Что самое безумное в твоих сохранённых рилсах?',
      'Если бы все увидели твоё экранное время — что бы их шокировало?',
      'За какую идею ты готов(а) умереть на холме?',
      'Какой твой самый используемый эмодзи и что это говорит о тебе?',
      'Самая дурная импульсивная покупка?',
      'Комплимент, который ты до сих пор вспоминаешь?',
      'Последняя мелкая ложь, которую ты сказал(а) сегодня?',
      'За что ты осуждаешь других, но делаешь сам(а)?',
      'Кто был твоим самым стыдным celebrity crush?',
      'Что самое хаотичное в твоей галерее прямо сейчас?',
      'Что бы ты изменил(а) в своём утреннем распорядке?',
      'Какой фильм ты притворяешься, что смотрел(а)?',
      'Самое худшее сообщение, которое ты отправлял(а) в личку?',
      'Самая случайная вещь, из-за которой ты плакал(а)?',
      'Кем ты хотел(а) быть в 10 лет?',
      'В какую теорию заговора ты немного веришь?',
      'У кого в этой группе лучшие мемы?',
    ],
    dare: [
      'Покажи последнее фото в галерее — без удалений',
      'Отправь голосовое с лучшей имитацией злодея из фильма',
      'Следующие 3 сообщения набери с закрытыми глазами и отправь как есть',
      'Группа выбирает тебе аватарку на час',
      'Скинь 7-е фото из галереи без контекста',
      'Голосовое: сделай пародию на кого-то из этой группы',
      'Скриншот экранного времени — в чат',
      'Селфи прямо сейчас, без фильтра',
      'Напиши «Мне нужно тебе кое-что сказать» третьему человеку в недавних чатах',
      'Пусть кто-то из группы запостит сторис с твоего аккаунта',
      'Голосовое: спой песню, которая застряла в голове',
      'Следующие 3 ответа — только гифками',
      'Поделись последним мемом, который кому-то отправлял(а)',
      'Смени био на то, что решит группа, на 30 минут',
      'Сделай комплимент каждому в этой группе прямо сейчас',
      'Прочитай своё последнее отправленное сообщение драматичным голосом',
      'Скриншот последнего чата (имена можно замазать)',
      'Следующие 5 сообщений — ТОЛЬКО КАПСОМ',
      'Запиши скороговорку на другом языке',
      'Скинь самое старое селфи, которое найдёшь в телефоне',
      'Группа пишет сообщение — ты отправляешь его лучшему другу',
      'Топ-3 самых прослушиваемых песни за неделю — в чат',
      'Скриншот заметок в телефоне — без редактирования',
      'Опиши каждого в группе одним эмодзи',
      'Голосовое шёпотом: расскажи забавный факт о себе',
      'Напиши последнему контакту «эй, думаю о тебе»',
      'Включи рандомную песню и скинь то, что заиграло',
      'Скинь скриншот самого стыдного уведомления на телефоне',
      'Следующие 5 сообщений — только вопросами',
      'Отправь стикер, который лучше всего описывает твоё настроение',
    ],
  },

  advanced: {
    truth: [
      'Самая большая ложь, которую ты говорил(а) близкому человеку?',
      'Кто был твоим последним крашем? Кто-то здесь его знает?',
      'Какая твоя самая токсичная черта?',
      'Ты когда-нибудь оставался в отношениях дольше, чем стоило?',
      'Что ты делал(а) пьяным(ой), о чём никому не рассказывал(а)?',
      'У кого из группы, по-твоему, лучшая личная жизнь?',
      'Ты когда-нибудь скринил(а) переписку, чтобы кому-то переслать?',
      'Самое плохое, что ты говорил(а) о ком-то за спиной?',
      'Кто тот человек, которого ты упустил(а)?',
      'Ты когда-нибудь ловил(а) чувства к кому-то из этой группы?',
      'Какой красный флаг ты игнорировал(а), потому что человек был красивый?',
      'Самое отчаянное, что ты делал(а) ради внимания?',
      'Ты встречался с кем-то, кого ненавидели твои друзья?',
      'Самый большой секрет, который ты скрываешь от семьи?',
      'Кому ты пишешь больше всего, и что бы подумали люди, прочитав ваш чат?',
      'Ты врал(а), чтобы отменить планы, а потом постил(а) в соцсети?',
      'Самое коварное, что ты делал(а) в приложении для знакомств?',
      'Кого ты последним сталкерил(а) в Instagram/Telegram?',
      'Притворялся(ась) офлайн, чтобы избежать кого-то?',
      'Какой совет по отношениям ты даёшь другим, но сам(а) не следуешь?',
      'Ты завидовал(а) кому-то из этой группы? В чём?',
      'Секрет, который ты расскажешь только в этом чате?',
      'Худшая отмазка, которой ты пользовался, чтобы отменить встречу?',
      'У тебя был друг, которого ты втайне терпеть не мог(ла)?',
      'Самое стыдное, за чем тебя застали?',
      'Кому ты позвонишь, если надо вытащить кого-то из участка в 3 ночи?',
      'Ты читал(а) чьи-то сообщения без ведома владельца?',
      'Какую границу ты пересёк(ла) и жалеешь?',
      'Если бы мы увидели твою историю прослушивания за вчерашний вечер — что бы нашли?',
      'Самое эмоционально отстранённое, что ты делал(а)?',
    ],
    dare: [
      "Напиши кому-то, с кем давно не общался: «Ты мне снился(ась)»",
      'Покажи экран блокировки — менять запрещено',
      'Группа смотрит твои подписки и спрашивает о любых 3 людях',
      'Голосовое: признайся в чём-то мелком, чего раньше не говорил(а)',
      'Напиши бывшему или старому крашу «привет» и скринь ответ',
      'Покажи последнего человека, которого искал(а) в Instagram/Telegram',
      'Кто-то из группы отправит одно сообщение с твоего аккаунта кому угодно',
      'Скриншот сохранённых постов — в чат',
      'Голосовое: скажи кому-то из группы, что ты реально о нём(ней) думаешь',
      'Покажи самое флиртовое сообщение, которое тебе присылали',
      'Скинь последнее полученное голосовое — без контекста',
      'Группа выбирает, кому ты отправишь комплимент голосовым',
      'Фото с тусовки, которое ты никогда бы не выложил(а) в основной аккаунт',
      'Скриншот: заряд батареи + последний искомый эмодзи',
      'Напиши кому-то «нам надо поговорить» и жди 5 минут, прежде чем объяснять',
      'Скриншот: сколько у тебя непрочитанных сообщений',
      'Группа выбирает песню — ты поёшь её в голосовом',
      'Фото себя ровно год назад',
      'Напиши фейковый подпис к thirst trap и кинь сюда',
      'Позвони кому-то из контактов на громкой и дай группе послушать 10 секунд',
      'Напиши последнему мэтчу в приложении знакомств что-нибудь дерзкое',
      'Самое хаотичное фото из недавно удалённых',
      'Горячий тейк, который разозлит кого-то здесь',
      'Аватарка меняется на ту, что выберет группа, на 2 часа',
      'Кто-то пишет твою следующую историю/статус в Telegram',
      'Голосовое: три хороших слова о человеке выше тебя',
      'Скинь guilty-pleasure плейлист, который ты от всех скрываешь',
      'Ответь огоньком на старую историю кого-то из группы',
      'Опиши свой типаж, не называя имён — группа угадывает, о ком ты',
      'Скриншот последнего товара, который ты добавил(а) в корзину',
    ],
  },

  spicy: {
    truth: [
      'Самое флиртовое сообщение, которое сейчас лежит в твоих личках?',
      'С кем из группы у тебя могло бы быть напряжение на вечеринке?',
      'Какой у тебя body count — или хотя бы что ты говоришь людям?',
      'Ты когда-нибудь отправлял(а) рискованное фото, о котором пожалел(а)?',
      'Что самое скандальное в твоих закрытых сторис?',
      'Кто последний снился тебе тот, кто не должен был?',
      'Самый скандальный поступок, о котором никто здесь не знает?',
      'Ты когда-нибудь был(а) «третьим лишним»?',
      'Что тебя заводит, но ты никому не рассказывал(а)?',
      'У кого в группе флиртовая энергетика, а сам(а) не знает?',
      'Что ты делал(а) на вечеринке, в чём не признаешься на трезвую?',
      'О ком ты думаешь, когда слышишь «а что если»?',
      'Ловил(а) чувства к тому, с кем планировал(а) только зависнуть?',
      'Самое прямое, что ты говорил(а) человеку, который тебе нравился?',
      'Сценарий-фантазия, о которой думаешь, но никогда бы не воплотил(а)?',
      'Притворялся(ась) заинтересованным ради чего-то?',
      'Самое рискованное место, где у тебя была близость?',
      'Что люди думают о твоей личной жизни — и в чём ошибаются?',
      'Кто был худшим целовальщиком в твоей жизни?',
      'Были чувства к двоим одновременно? Кто победил?',
      'Самое стыдное, что случалось на свидании?',
      'Если бы одна ночь без последствий — с кем?',
      'Самый дерзкий ход, который ты делал(а) на кого-то?',
      'Пользовался(ась) чьим-то Netflix/Spotify после расставания?',
      'Какое сообщение в личке шокировало бы эту группу?',
      'Первое, на что ты обращаешь внимание во внешности?',
      'Врал(а) о том, где ночевал(а)?',
      'Самый безумный поступок из ревности?',
      'Если бы у твоего ситуативного романа был статус — что бы он гласил?',
      'У кого в группе, по-твоему, самая интересная личная жизнь?',
    ],
    dare: [
      'Отправь своё самое горячее селфи в этот чат — владей моментом',
      'Напиши кому-то из группы то, что сказал(а) бы только в 2 ночи',
      'Покажи группе последние 3 личных сообщения (чат выбираешь сам(а), но не редактируй)',
      'Голосовое: подробно опиши свой типаж — группа угадывает, кто подходит',
      'Скинь самое дерзкое фото с телефона — или группа выбирает аватарку на 3 часа',
      'Напиши крашу или ситуативному партнёру «приезжай» и скринь ответ',
      'Покажи последний эмодзи, который ты использовал(а) во флирте',
      'Группа пишет пикап-фразу — ты отправляешь её кому-нибудь в личку',
      'Голосовое самым флиртовым голосом — скажи что угодно',
      'Скинь песню, которая напоминает о ком-то, с кем ты был(а) — без контекста',
      'Оцени всех в группе от 1 до 10 по «загадочной энергетике» — только голосовым',
      'Thirst trap селфи в этот чат — не удалять 10 минут',
      'Кто-то выбирает контакт — ты отправляешь ему огонёк без объяснений',
      'Опиши свой последний ситуативный роман ровно в 5 словах',
      'Голосовое: самый горячий тейк о том, что делает людей привлекательными',
      'Покажи самый дерзкий текст, который ты отправлял(а) кому-то, кто нравился',
      'Группа пишет твоё био для приложения знакомств на 24 часа',
      'Голосовое: прочитай последнее флиртовое сообщение, которое отправлял(а)',
      'Выбери кого-то из группы и скажи ему(ей) самый искренний комплимент голосовым',
      'Скриншот своего «типажа» — знаменитость, персонаж или эстетика',
      'Напиши кому-нибудь «не могу перестать думать о тебе» и покажи ответ',
      'Шепни что-нибудь в голосовом, что сказал(а) бы только лично',
      'Самый хаотичный скриншот с телефона — группа решает, останется ли он',
      'Отправь 🔥 трём людям в личках без объяснений',
      'Группа дарит тебе — отправь любому любое сообщение, одно вето',
      'Фото текущего аутфита — группа оценивает',
      'Голосовое: «ты мне нравишься» на трёх языках',
      'Скинь свою самую прослушиваемую ночную песню — не ври',
      'Расскажи свой последний сон о ком-то, не называя имени — группа угадывает',
      'Запости «кинь 🔥, если считаешь меня привлекательным(ой)» в сторис и скринь результат',
    ],
  },
};

// ─── Chinese ─────────────────────────────────────────────────────────────────

const ZH: TieredQuestionBank = {
  icebreaker: {
    truth: [
      '你最后搜索的一条记录是什么？老实说',
      '你一直在假装拥有什么技能？',
      '你歌单里最社死的一首歌是什么？',
      '群里谁的生活你最想体验一天？',
      '你在 YouTube/B站 看过最离谱的兔子洞是什么？',
      '你最离谱的食物观点是什么？',
      '你在哪个 App 上浪费时间最多？',
      '你私下觉得哪个潮流特别蠢？',
      '如果搜索记录被公开，什么会让你社死？',
      '你对什么事情有莫名的胜负欲？',
      '你因为什么奇葩理由取关过别人？',
      '你最长刷过别人的主页刷到多远？',
      '你在个人简介或社交资料上撒过什么谎？',
      '你收藏夹里最离谱的内容是什么？',
      '如果群里所有人能看到你的屏幕使用时间，什么会让他们震惊？',
      '你最坚持的一个观点是什么？',
      '你最常用的 emoji 是什么？这说明了什么？',
      '你做过的最冲动的消费是什么？',
      '你收到过什么夸奖到现在还在回味？',
      '你今天说的最后一个善意的谎言是什么？',
      '你嘴上批评别人但自己也在做的事是什么？',
      '你最社死的明星暗恋对象是谁？',
      '你相册里现在最混乱的一张照片是什么？',
      '你最想改变早晨习惯的哪一点？',
      '你假装看过但其实从没看过的电影是什么？',
      '你发过的最尴尬的私信是什么？',
      '你为了什么莫名其妙的事情哭过？',
      '你 10 岁时的梦想是什么？',
      '你有点相信的阴谋论是什么？',
      '群里谁的表情包最好笑？',
    ],
    dare: [
      '亮出相册最后一张照片——不许先删',
      '发语音模仿电影反派',
      '接下来 3 条消息闭眼打字，原样发出',
      '让群友给你选头像，保持一小时',
      '发出相册第 7 张照片，不解释',
      '语音模仿群里某个人的说话方式',
      '截图你的屏幕使用时间发出来',
      '现在拍一张自拍发出来，不修不滤',
      '给最近聊天列表第 3 个人发"我有件事想跟你说"',
      '让群里某人用你的账号发一条动态',
      '语音唱你脑子里正在循环的歌',
      '接下来 3 条消息只能用 GIF 回复',
      '分享你最后发给别人的表情包',
      '让群友给你改签名，保持 30 分钟',
      '现在给群里每个人发一条夸奖',
      '用戏剧性的语气语音朗读你最后发的一条消息',
      '截图你最近的一个聊天（名字可以打码）',
      '接下来 5 条消息必须全部大写/加感叹号',
      '录一段外语绕口令语音',
      '发出你手机里能找到的最老的自拍',
      '群友写消息，你发给你最好的朋友',
      '分享你本周播放量前三的歌',
      '截图你的备忘录——不编辑',
      '用一个 emoji 形容群里每个人',
      '语音悄悄话：说一个关于你自己的冷知识',
      '给最近联系人发"嘿，想你了"',
      '随机播放音乐，分享播到的第一首',
      '截图你手机上最尴尬的通知',
      '接下来 5 条消息只能用问句',
      '发一个最能代表你现在心情的贴纸',
    ],
  },

  advanced: {
    truth: [
      '你对在乎的人说过的最大的谎是什么？',
      '你上一个暗恋对象是谁？群里有人认识吗？',
      '你知道自己最 toxic 的特质是什么？',
      '你有没有在一段关系里待得比应该的更久？',
      '你喝醉后做过什么从没告诉任何人的事？',
      '你觉得群里谁的感情生活最精彩？',
      '你截过别人的聊天记录转发给第三个人吗？',
      '你在背后说过别人的最狠的话是什么？',
      '谁是你错过的那个人？',
      '你对群里的人动过心吗？',
      '你因为对方好看而忽略过什么红旗？',
      '你为了吸引注意力做过的最拼的事是什么？',
      '你交往过朋友们都讨厌的人吗？',
      '你瞒着家人的最大秘密是什么？',
      '你和谁聊天最频繁？如果别人看到那些聊天记录会怎么想？',
      '你撒谎推掉过约会然后发了社交动态吗？',
      '你在交友软件上做过最阴的操作是什么？',
      '你最近偷看过谁的 Instagram/Telegram 主页？',
      '你假装不在线来躲避过谁？',
      '你给别人的恋爱建议但自己从不遵守的是什么？',
      '你嫉妒过群里的谁？关于什么？',
      '只在这个群里说的秘密？',
      '你用过的最烂的推掉约会的借口？',
      '你有过私下忍受不了的朋友吗？',
      '你被人抓到过最尴尬的事是什么？',
      '凌晨三点需要保释谁，你会打给谁？',
      '你偷看过别人的消息吗？',
      '你后悔越过的一条界线是什么？',
      '如果我们能看到你昨晚的播放历史，会发现什么？',
      '你做过的最冷漠的事是什么？',
    ],
    dare: [
      '给一个好久没联系的人发"你出现在我梦里了"',
      '亮出锁屏——不许换',
      '群友翻你的关注列表，问你任意 3 个人是谁',
      '语音坦白一件你从没承认过的小事',
      '给前任或老暗恋对象发"嘿"然后截图结果',
      '展示你最后在 Instagram/Telegram 搜索的人',
      '群里某人用你的账号给任何人发一条消息',
      '截图你的收藏/书签发出来',
      '语音告诉群里某人你对 ta 的真实看法',
      '展示你收到过的最撩人的私信',
      '发出你最后收到的语音——不加上下文',
      '群友选人，你给那个人发一条语音夸奖',
      '发一张你绝不会发到主号的聚会照片',
      '截图：手机电量 + 最后搜索的 emoji',
      '给某人发"我们得谈谈"然后等 5 分钟再解释',
      '截图你有多少未读消息',
      '群友选歌，你语音唱',
      '发一张你一年前的照片',
      '写一条假的 thirst trap 文案发到群里',
      '打开免提给通讯录里的人打电话，群友听 10 秒',
      '给你上次在交友软件匹配的人发点什么大胆的',
      '最近删除里最混乱的一张照片',
      '说一个可能让群里某人生气的犀利观点',
      '头像换成群友投票选的，保持 2 小时',
      '让某人代写你的下一条 Telegram 动态',
      '语音：对上面那个人说三句好话',
      '分享你偷偷藏起来的 guilty pleasure 歌单',
      '给群里某人的旧动态回复一个火焰 emoji',
      '描述你的理想型但不说名字——群友猜你想的是谁',
      '截图你网购最后加入购物车的东西',
    ],
  },

  spicy: {
    truth: [
      '你私信里现在最暧昧的消息是什么？',
      '群里谁跟你在派对上最可能产生暧昧张力？',
      '你的 body count 是多少——或者至少你告诉别人是多少？',
      '你发过什么让你后悔的大尺度照片吗？',
      '你的小号/私密动态里最劲爆的内容是什么？',
      '你最近梦到了谁——一个不该梦到的人？',
      '你做过的最 scandal 的事，群里没人知道的？',
      '你当过"第三者"吗？',
      '你最大的 turn-on 是什么，从没告诉过任何人的？',
      '群里谁有 flirty 气场但自己不知道？',
      '你在派对上做过什么清醒时绝不会承认的事？',
      '听到"如果当初"你会想到谁？',
      '你对一个本来只想 hook up 的人动过真心吗？',
      '你对喜欢的人说过的最直接的话是什么？',
      '你脑子里经常出现但永远不会付诸行动的幻想？',
      '你假装对某人感兴趣只是为了得到什么？',
      '你在最冒险的地方亲密过是哪里？',
      '别人对你感情生活的误解是什么？',
      '你经历过的最差的 kisser 是谁？',
      '你同时对两个人有感觉过吗？谁赢了？',
      '约会中发生过的最尴尬的事？',
      '如果可以没有后果地和任何人过一晚——选谁？',
      '你对谁用过的最大胆的撩人招数是什么？',
      '分手后还在用对方的 Netflix/会员吗？',
      '你私信里哪条消息会让这个群震惊？',
      '你对有好感的人第一个注意到的身体特征是什么？',
      '你撒谎说过昨晚睡在哪吗？',
      '你嫉妒的时候做过的最疯的事？',
      '如果你的暧昧对象有一个状态更新，会写什么？',
      '你觉得群里谁的私生活最精彩？',
    ],
    dare: [
      '发你最好看的自拍到群里——大胆拥有它',
      '给群里某人发一条只有凌晨 2 点才会说的话',
      '让群友看你最近 3 条私信（你选哪个聊天，但不能编辑）',
      '语音详细描述你的理想型——群友猜谁符合',
      '发你手机里最 spicy 的照片——否则群友选你头像 3 小时',
      '给暗恋对象或暧昧对象发"过来"然后截图回复',
      '展示你最后在暧昧聊天里用的 emoji',
      '群友写一句搭讪词，你发给某人',
      '用你最撩人的声音发一条语音——内容随便',
      '分享一首让你想起某个前任/暧昧的歌——不解释',
      '给群里每个人的"神秘感"打 1-10 分——只能用语音',
      '发一张自拍到群里——10 分钟内不能删',
      '群友选一个联系人，你给 ta 发一个火焰 emoji 不解释',
      '用恰好 5 个字形容你上一段暧昧关系',
      '语音：关于"什么让人有吸引力"说出你最犀利的观点',
      '展示你发给喜欢的人的最大胆的文字',
      '群友帮你写交友软件 bio，保持 24 小时',
      '语音朗读你最后发出的暧昧消息——不编辑',
      '选群里一个人，语音给 ta 你最真诚的夸奖',
      '截图你的"理想型"——明星、角色或审美风格',
      '给某人发"我没法不想你"然后展示回复',
      '语音悄悄话：说一句你只会当面说的话',
      '手机里最混乱的截图——群友决定留不留',
      '给私信里 3 个人发 🔥，不解释',
      '群友给你出一个 dare——你发给任何人，有一次否决权',
      '发你现在穿搭的照片——群友打分',
      '语音用三种语言说"我喜欢你"',
      '分享你深夜最常循环的歌——不准撒谎',
      '描述你最近关于某人的梦，不说名字——群友猜',
      '发一条动态"觉得我有吸引力的扔个🔥"然后截图结果',
    ],
  },
};

// ─── Exports ─────────────────────────────────────────────────────────────────

export const QUESTIONS_BY_LANG: Record<string, TieredQuestionBank> = {
  en: EN,
  ru: RU,
  zh: ZH,
};

/**
 * Pick a random question for the given language, tier, and type.
 * Accepts an optional `usedSet` to avoid repeats within a session.
 * Uses crypto.randomInt for uniform distribution.
 */
export function pickQuestion(
  lang: string,
  tier: TodTier,
  type: 'truth' | 'dare',
  usedSet?: Set<string>,
): string {
  const bank = QUESTIONS_BY_LANG[lang] ?? QUESTIONS_BY_LANG.en;
  const list = bank[tier][type];

  // Filter out already-used questions
  let candidates = usedSet
    ? list.filter((q) => !usedSet.has(q))
    : list;

  // If all questions exhausted, reset (allow repeats)
  if (candidates.length === 0) {
    usedSet?.clear();
    candidates = list;
  }

  const picked = candidates[randomInt(0, candidates.length)];
  usedSet?.add(picked);
  return picked;
}
